name: Build Python Container

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        run: |
          sudo mkdir ~/.aws; \
            echo -e "[default]\n" | sudo tee -a ~/.aws/credentials; \
            echo -e "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\n" | sudo tee -a ~/.aws/credentials; \
            echo -e "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}\n" | sudo tee -a ~/.aws/credentials;

      - name: Configure AWS config
        run: |
          echo -e "[default]\n" | sudo tee -a ~/.aws/config; \
            echo -e "region = eu-west-1\n" | sudo tee -a ~/.aws/config;

      - name: Swap in NTFY URL
        run: sed -i 's/ntftUrlHerePlease/${{ secrets.NTFY_URL }}/' main.py

      - name: Swap in NTFY username
        run: sed -i 's/ntfyUsernameHerePlease/${{ secrets.NTFY_USER }}/' main.py

      - name: Swap in NTFY password
        run: sed -i 's/ntfyPasswordHerePlease/${{ secrets.NTFY_PASS }}/' main.py
      
      - name: Docker build
        run: docker build . -t 550661752655.dkr.ecr.eu-west-1.amazonaws.com/filmmon:latest

      - name: Log in to ECR
        run: aws ecr get-login-password --region region | docker login --username AWS --password-stdin 550661752655.dkr.ecr.eu-west-1.amazonaws.com

      - name: Push to ECR
        run: docker push 550661752655.dkr.ecr.eu-west-1.amazonaws.com/filmmon:latest
          